// TShock 配置文件字段 schema 定义
// type: 'boolean' | 'number' | 'string' | 'select' | 'color' | 'dict' | 'json'
// color: 值为 [R, G, B] 整数数组
// dict:  值为 { key: { Username, UserGroupName } } 对象（REST Token）
// json:  值为任意 JSON，渲染为可编辑 textarea

export const CONFIG_SCHEMA = [
  // ── 基本设置 ──────────────────────────────────────────────────────
  { key: 'ServerPort',                  type: 'number',  default: 7777,    category: '基本设置',   description: '服务器运行的端口。 * **字段类型**: `Int32` * **默认值**: `7777`' },
  { key: 'MaxSlots',                    type: 'number',  default: 8,       category: '基本设置',   description: '最大同时连接的客户端数量。 如果你希望玩家在服务器满员时被踢出并显示“服务器已满”，请将此值设置为你希望的最大玩家数量，然后将泰拉瑞亚的最大玩家数量设置为比此值高2。 * **字段类型**: `Int32` * **默认值**: `8`' },
  { key: 'ReservedSlots',               type: 'number',  default: 20,      category: '基本设置',   description: '超出服务器最大玩家数的预留位数量（这些预留位仅允许预留玩家加入）。 * **字段类型**: `Int32` * **默认值**: `20`' },
  { key: 'ServerPassword',              type: 'string',  default: '',      category: '基本设置',   description: '加入服务器所需的服务器密码。 * **字段类型**: `String` * **默认值**: ``' },
  { key: 'ServerName',                  type: 'string',  default: '',      category: '基本设置',   description: '若UseServerName设置为true，则在会话期间替换世界名称。 * **字段类型**: `String` * **默认值**: ``' },
  { key: 'UseServerName',               type: 'boolean', default: false,   category: '基本设置',   description: '是否使用服务器名称（ServerName）替代世界名称。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'ServerFullReason',            type: 'string',  default: 'Server is full', category: '基本设置', description: '当服务器已满时，踢出尝试加入的玩家的理由。 * **字段类型**: `String` * **默认值**: `Server is full`' },
  { key: 'ServerFullNoReservedReason',  type: 'string',  default: 'Server is full. No reserved slots open.', category: '基本设置', description: '当服务器已满且没有预留玩家空位可用时，踢出尝试加入的玩家的理由。 * **字段类型**: `String` * **默认值**: `Server is full. No reserved slots open.`' },
  { key: 'EnableWhitelist',             type: 'boolean', default: false,   category: '基本设置',   description: '根据whitelist.txt文件中的IP地址启用或禁用白名单。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'WhitelistKickReason',         type: 'string',  default: 'You are not on the whitelist.', category: '基本设置', description: '当玩家因未加入白名单而被踢出时显示的原因。 * **字段类型**: `String` * **默认值**: `You are not on the whitelist.`' },
  { key: 'WorldTileProvider',           type: 'select',  default: 'default', options: ['default', 'constileation', 'heaptile'], category: '基本设置', description: '允许更改默认的世界图块生成器。有效类型包括："default", "constileation"和"heaptile"。 * **字段类型**: `String` * **默认值**: `default`' },

  // ── 登录注册 ──────────────────────────────────────────────────────
  { key: 'RequireLogin',                type: 'boolean', default: false,   category: '登录注册',   description: '要求所有玩家在被允许玩游戏之前注册或登录。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'AllowLoginAnyUsername',       type: 'boolean', default: true,    category: '登录注册',   description: '允许用户登录任何账户，即使用户名与角色名称不匹配。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'AllowRegisterAnyUsername',    type: 'boolean', default: false,   category: '登录注册',   description: '允许用户注册不一定与角色名称匹配的用户名。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'BCryptWorkFactor',            type: 'number',  default: 7,       category: '登录注册',   description: '确定使用的BCrypt工作因子。如果增加，所有密码将在验证时升级到新的工作因子。计算轮数为2^n。请谨慎增加。范围：5-31。 * **字段类型**: `Int32` * **默认值**: `7`' },
  { key: 'MinimumPasswordLength',       type: 'number',  default: 4,       category: '登录注册',   description: '新用户帐户的最小密码长度。不能少于4。 * **字段类型**: `Int32` * **默认值**: `4`' },
  { key: 'MaximumLoginAttempts',        type: 'number',  default: 3,       category: '登录注册',   description: '踢出玩家之前的失败登录尝试次数。 * **字段类型**: `Int32` * **默认值**: `3`' },
  { key: 'DisableUUIDLogin',            type: 'boolean', default: false,   category: '登录注册',   description: '防止用户使用其客户端UUID登录。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'KickEmptyUUID',               type: 'boolean', default: false,   category: '登录注册',   description: '踢出没有向服务器发送其UUID的客户端。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'DisableLoginBeforeJoin',      type: 'boolean', default: false,   category: '登录注册',   description: '防止用户在完成连接之前登录。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'DefaultGuestGroupName',       type: 'string',  default: 'guest', category: '登录注册',   description: '未注册玩家默认的组名 * **字段类型**: `String` * **默认值**: `guest`' },
  { key: 'DefaultRegistrationGroupName',type: 'string',  default: 'default',category: '登录注册',  description: '新注册用户默认的组名 * **字段类型**: `String` * **默认值**: `default`' },

  // ── 世界保护 ──────────────────────────────────────────────────────
  { key: 'DisableBuild',                type: 'boolean', default: false,   category: '世界保护',   description: '禁用任何放置或移除物块。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'SpawnProtection',             type: 'boolean', default: true,    category: '世界保护',   description: '防止在重生保护范围的默认出生点内放置物块。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'SpawnProtectionRadius',       type: 'number',  default: 10,      category: '世界保护',   description: '受重生保护范围设置保护的出生点周围的物块半径。 * **字段类型**: `Int32` * **默认值**: `10`' },
  { key: 'RangeChecks',                 type: 'boolean', default: true,    category: '世界保护',   description: '根据玩家与其放置的方块之间的距离（似乎不止），启用或禁用反作弊距离检查。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'AllowCorruptionCreep',        type: 'boolean', default: true,    category: '世界保护',   description: '允许腐化蔓延。`*` * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'AllowCrimsonCreep',           type: 'boolean', default: true,    category: '世界保护',   description: '允许猩红蔓延。`*` * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'AllowHallowCreep',            type: 'boolean', default: true,    category: '世界保护',   description: '允许神圣蔓延。`*` * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'DisableHardmode',             type: 'boolean', default: false,   category: '世界保护',   description: '如果启用，血肉墙 或 /starthardmode 命令将不会激活困难模式。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'RegionProtectChests',         type: 'boolean', default: false,   category: '世界保护',   description: '区域保护是否应用于箱子。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'RegionProtectGemLocks',       type: 'boolean', default: true,    category: '世界保护',   description: '区域保护是否应用于宝石锁。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'AllowIce',                    type: 'boolean', default: false,   category: '世界保护',   description: '允许在通常无法建造的地方放置冰。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'AllowCutTilesAndBreakables',  type: 'boolean', default: false,   category: '世界保护',   description: '允许玩家在通常无法建造的地方破坏临时方块（草、罐子等）。`x` * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'IgnoreChestStacksOnLoad',     type: 'boolean', default: false,   category: '世界保护',   description: '允许在世界加载期间，箱子中的物品堆叠数量超过堆叠上限。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'PreventBannedItemSpawn',      type: 'boolean', default: false,   category: '世界保护',   description: '防止禁止物品被生成或通过命令给予。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'AllowAllowedGroupsToSpawnBannedItems', type: 'boolean', default: false, category: '世界保护', description: '即使设置了 PreventBannedItemSpawn 为 true，也允许“禁止物品允许列表中的组”生成禁止物品。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'ForceHalloween',              type: 'boolean', default: false,   category: '世界保护',   description: '强制全年开启万圣节专属活动。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'ForceXmas',                   type: 'boolean', default: false,   category: '世界保护',   description: '强制全年开启圣诞节专属活动。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'ForceTime',                   type: 'select',  default: 'normal', options: ['normal', 'day', 'night'], category: '世界保护', description: '强制世界时间设置为正常、白天或夜晚(normal, day, or night)。 * **字段类型**: `String` * **默认值**: `normal`' },

  // ── 玩家游戏 ──────────────────────────────────────────────────────
  { key: 'MaxHP',                       type: 'number',  default: 500,     category: '玩家游戏',   description: '玩家在装备增益之前可以拥有的最大HP。 * **字段类型**: `Int32` * **默认值**: `500`' },
  { key: 'MaxMP',                       type: 'number',  default: 200,     category: '玩家游戏',   description: '玩家在装备增益之前可以拥有的最大MP。 * **字段类型**: `Int32` * **默认值**: `200`' },
  { key: 'MaxDamage',                   type: 'number',  default: 1175,    category: '玩家游戏',   description: '玩家/NPC可造成的最大伤害值。 * **字段类型**: `Int32` * **默认值**: `1175`' },
  { key: 'MaxProjDamage',               type: 'number',  default: 1175,    category: '玩家游戏',   description: '射弹可以造成的最大伤害 * **字段类型**: `Int32` * **默认值**: `1175`' },
  { key: 'RespawnSeconds',              type: 'number',  default: 0,       category: '玩家游戏',   description: '玩家重生前必须等待的秒数。有效范围：0（默认值）至15秒。使用时风险自负。 * **字段类型**: `Int32` * **默认值**: `0`' },
  { key: 'RespawnBossSeconds',          type: 'number',  default: 0,       category: '玩家游戏',   description: '当附近存在Boss时，玩家重生前必须等待的秒数。有效范围：0（默认值）至30秒。使用时风险自负。 * **字段类型**: `Int32` * **默认值**: `0`' },
  { key: 'InfiniteInvasion',            type: 'boolean', default: false,   category: '玩家游戏',   description: '启用永无止境的入侵事件。你仍然需要启动事件，例如使用 /invade 命令。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'InvasionMultiplier',          type: 'number',  default: 1,       category: '玩家游戏',   description: '确定入侵事件的大小。 计算入侵大小的公式是100 + (倍数 * (血量大于200的活跃玩家的数量)) * **字段类型**: `Int32` * **默认值**: `1`' },
  { key: 'PvPMode',                     type: 'select',  default: 'normal', options: ['normal', 'always', 'pvpwithnoteam', 'disabled'], category: '玩家游戏', description: '设置PvP模式。有效类型包括："normal"（正常）、"always"（始终开启），"pvpwithnoteam"（始终开启且禁止组队）和"disabled"（禁用）。 * **字段类型**: `String` * **默认值**: `normal`' },
  { key: 'RememberLeavePos',            type: 'boolean', default: false,   category: '玩家游戏',   description: '根据玩家的IP地址记录其退出时的位置（服务器重启后不保留）。 例如：当您尝试断开连接并重新连接时，通常会被自动回到到出生点，但此时您仍会停留在上次离开时的位置。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'GiveItemsDirectly',           type: 'boolean', default: false,   category: '玩家游戏',   description: '如果设置为true，将直接将给予玩家的物品插入到他们的背包中。需要SSC。否则，给予玩家的物品将作为掉落物品生成。实验性功能。可能无法正确工作或导致物品丢失 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'MaxRangeForDisabled',         type: 'number',  default: 10,      category: '玩家游戏',   description: '被禁用玩家可以移动的最大距离，以物块为单位。 * **字段类型**: `Int32` * **默认值**: `10`' },
  { key: 'DefaultMaximumSpawns',        type: 'number',  default: 5,       category: '玩家游戏',   description: '每波将生成的怪物默认最大数量。数值越高，波次中的怪物就越多（最大刷怪量） * **字段类型**: `Int32` * **默认值**: `5`' },
  { key: 'DefaultSpawnRate',            type: 'number',  default: 600,     category: '玩家游戏',   description: '波次之间的延迟。值越低，怪物越多（刷怪速率）。 * **字段类型**: `Int32` * **默认值**: `600`' },
  { key: 'StatueSpawn200',              type: 'number',  default: 3,       category: '玩家游戏',   description: '一个雕像在200像素(?)(12.5格)内可以生成的NPC数量，之后才会停止生成。 默认 = 3。 * **字段类型**: `Int32` * **默认值**: `3`' },
  { key: 'StatueSpawn600',              type: 'number',  default: 6,       category: '玩家游戏',   description: '一个雕像在600像素(?)(37.5格)内可以生成的NPC数量，之后才会停止生成。 默认 = 6。 * **字段类型**: `Int32` * **默认值**: `6`' },
  { key: 'StatueSpawnWorld',            type: 'number',  default: 10,      category: '玩家游戏',   description: '一个雕像可以生成的NPC总数，之后才会停止生成。 默认 = 10。 * **字段类型**: `Int32` * **默认值**: `10`' },
  { key: 'HardcoreOnly',               type: 'boolean', default: false,   category: '玩家游戏',   description: '防止非硬核模式玩家连接游戏。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'MediumcoreOnly',             type: 'boolean', default: false,   category: '玩家游戏',   description: '阻止软核玩家连接服务器。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'SoftcoreOnly',               type: 'boolean', default: false,   category: '玩家游戏',   description: '禁止非软核玩家连接。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'KickOnHardcoreDeath',        type: 'boolean', default: false,   category: '玩家游戏',   description: '硬核模式玩家死亡时是否踢出。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'BanOnHardcoreDeath',         type: 'boolean', default: false,   category: '玩家游戏',   description: '是否在硬核模式玩家死亡时将其封禁。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'HardcoreKickReason',         type: 'string',  default: 'Death results in a kick', category: '玩家游戏', description: '硬核模式玩家死亡被踢出时显示的被踢出原因。 * **字段类型**: `String` * **默认值**: `Death results in a kick`' },
  { key: 'HardcoreBanReason',          type: 'string',  default: 'Death results in a ban',  category: '玩家游戏', description: '硬核模式玩家死亡被封禁时时显示的被封禁原因。 * **字段类型**: `String` * **默认值**: `Death results in a ban`' },
  { key: 'KickOnMediumcoreDeath',      type: 'boolean', default: false,   category: '玩家游戏',   description: '中核模式玩家死亡时是否踢出。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'BanOnMediumcoreDeath',       type: 'boolean', default: false,   category: '玩家游戏',   description: '是否在中核模式玩家死亡时将其封禁。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'MediumcoreKickReason',       type: 'string',  default: 'Death results in a kick', category: '玩家游戏', description: '中核模式玩家死亡被踢出时显示的被踢出原因。 * **字段类型**: `String` * **默认值**: `Death results in a kick`' },
  { key: 'MediumcoreBanReason',        type: 'string',  default: 'Death results in a ban',  category: '玩家游戏', description: '中核模式玩家死亡被封禁时显示的被封禁原因。 * **字段类型**: `String` * **默认值**: `Death results in a ban`' },

  // ── 聊天设置 ──────────────────────────────────────────────────────
  { key: 'ChatFormat',                  type: 'string',  default: '{1}{2}{3}: {4}', category: '聊天设置', description: '更改游戏内聊天格式：{0} = 组名，{1} = 组前缀，{2} = 玩家名，{3} = 组后缀，{4} = 聊天消息。 * **字段类型**: `String` * **默认值**: `{1}{2}{3}: {4}`' },
  { key: 'ChatAboveHeadsFormat',        type: 'string',  default: '{2}',  category: '聊天设置',   description: '在使用头顶聊天时更改玩家名称。以玩家名称开头，并用方括号括起来，遵循泰拉瑞亚的格式。 与ChatFormat格式相同，但不包含消息内容。 * **字段类型**: `String` * **默认值**: `{2}`' },
  { key: 'EnableChatAboveHeads',        type: 'boolean', default: false,  category: '聊天设置',   description: '是否在玩家头顶显示聊天消息。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'AllowCtTag',                  type: 'boolean', default: false,  category: '聊天设置',   description: '允许玩家在聊天中使用 [ct:] 标签。注意：错误的 [ct:] 标签可能导致移动端客户端崩溃 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'MaximumChatMessageLength',    type: 'number',  default: 500,    category: '聊天设置',   description: '聊天消息的最大允许长度。范围：250-2000 * **字段类型**: `Int32` * **默认值**: `500`' },
  { key: 'TruncateExcessiveChatMessages',type:'boolean', default: false,  category: '聊天设置',   description: '若聊天消息长度超过 MaximumChatMessageLength 的设定值，是否截断该消息后发送 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'CommandSpecifier',            type: 'string',  default: '/',    category: '聊天设置',   description: '指定以哪个字符串开始执行命令。 注意：如果字符串长度大于1，则无法正常工作。 * **字段类型**: `String` * **默认值**: `/`' },
  { key: 'CommandSilentSpecifier',      type: 'string',  default: '.',    category: '聊天设置',   description: '指定以哪个字符串开始静默执行命令。 注意：如果字符串长度大于1，则无法正常工作。 * **字段类型**: `String` * **默认值**: `.`' },
  { key: 'BroadcastRGB',               type: 'color',   default: [255, 255, 255], category: '聊天设置', description: '用于广播消息颜色的RGB值。 #.#.# = 红/蓝/绿 最大值：255 * **字段类型**: `Int32[]` * **默认值**: `System.Int32[]`' },
  { key: 'SuperAdminChatPrefix',        type: 'string',  default: '(Super Admin) ', category: '聊天设置', description: '超级管理员聊天前缀。 * **字段类型**: `String` * **默认值**: `(Super Admin) `' },
  { key: 'SuperAdminChatSuffix',        type: 'string',  default: '',     category: '聊天设置',   description: 'superadmin组的聊天后缀. * **字段类型**: `String` * **默认值**: ``' },
  { key: 'SuperAdminChatRGB',           type: 'color',   default: [255, 0, 0], category: '聊天设置', description: '超级管理员组的聊天颜色。#.#.# = 红/蓝/绿 最大值：255 * **字段类型**: `Int32[]` * **默认值**: `System.Int32[]`' },
  { key: 'AnonymousBossInvasions',      type: 'boolean', default: true,   category: '聊天设置',   description: '是否在Boss生成或入侵开始时进行公告。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'EnableGeoIP',                 type: 'boolean', default: false,  category: '聊天设置',   description: '是否根据玩家的IP在加入时宣布玩家的地理位置。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'KickProxyUsers',              type: 'boolean', default: true,   category: '聊天设置',   description: '如果启用了GeoIP，将踢出被检测到使用代理的用户。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'AnnounceSave',                type: 'boolean', default: true,   category: '聊天设置',   description: '启用或禁用世界保存广播。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'ShowBackupAutosaveMessages',  type: 'boolean', default: true,   category: '聊天设置',   description: '是否显示备份自动保存消息。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'DisplayIPToAdmins',           type: 'boolean', default: false,  category: '聊天设置',   description: '向具有日志权限的用户显示玩家的IP地址。 * **字段类型**: `Boolean` * **默认值**: `False`' },

  // ── 反作弊 ────────────────────────────────────────────────────────
  { key: 'TileKillThreshold',           type: 'number',  default: 60,     category: '反作弊',     description: '如果在1秒内方块破坏次数超过此数值，则禁用玩家并回滚其操作。 * **字段类型**: `Int32` * **默认值**: `60`' },
  { key: 'TilePlaceThreshold',          type: 'number',  default: 32,     category: '反作弊',     description: '如果在1秒内方块放置次数超过此数值，则禁用玩家并回滚其操作。 * **字段类型**: `Int32` * **默认值**: `32`' },
  { key: 'TileLiquidThreshold',         type: 'number',  default: 50,     category: '反作弊',     description: '如果在1秒内液体放置次数超过此数值，则禁用该玩家。 * **字段类型**: `Int32` * **默认值**: `50`' },
  { key: 'TilePaintThreshold',          type: 'number',  default: 15,     category: '反作弊',     description: '如果在1秒内涂色方块次数超过此数值，则禁用该玩家。 * **字段类型**: `Int32` * **默认值**: `15`' },
  { key: 'ProjectileThreshold',         type: 'number',  default: 50,     category: '反作弊',     description: '若玩家在1秒内生成的射弹数量达到此值，则将其禁用。 * **字段类型**: `Int32` * **默认值**: `50`' },
  { key: 'HealOtherThreshold',          type: 'number',  default: 50,     category: '反作弊',     description: '如果在1秒内发送此数量的HealOtherPlayer数据包，则禁用该玩家。 * **字段类型**: `Int32` * **默认值**: `50`' },
  { key: 'KickOnTileKillThresholdBroken',  type: 'boolean', default: false, category: '反作弊',   description: '当用户超过方块破坏阈值时是否踢出。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'KickOnTilePlaceThresholdBroken', type: 'boolean', default: false, category: '反作弊',   description: '当用户超过方块放置阈值时是否踢出。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'KickOnTileLiquidThresholdBroken',type: 'boolean', default: false, category: '反作弊',   description: '当用户超过液体操作阈值时是否踢出。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'KickOnTilePaintThresholdBroken', type: 'boolean', default: false, category: '反作弊',   description: '当用户超过方块刷漆阈值时是否踢出。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'KickOnProjectileThresholdBroken',type: 'boolean', default: false, category: '反作弊',   description: '当用户超过射弹阈值时是否踢出。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'KickOnHealOtherThresholdBroken', type: 'boolean', default: false, category: '反作弊',   description: '当用户超过治疗他人阈值时是否踢出。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'KickOnDamageThresholdBroken',    type: 'boolean', default: false, category: '反作弊',   description: '当用户超过最大伤害阈值时是否踢出。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'ProjIgnoreShrapnel',          type: 'boolean', default: true,   category: '反作弊',     description: '是否在射弹阈值计数中忽略水晶子弹的碎片。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'IgnoreProjKill',              type: 'boolean', default: false,  category: '反作弊',     description: '忽略检查玩家是否“可以”摧毁射弹。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'IgnoreProjUpdate',            type: 'boolean', default: false,  category: '反作弊',     description: '忽略检查玩家是否“可以”更新射弹。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'DisableInvisPvP',             type: 'boolean', default: false,  category: '反作弊',     description: '在启用PvP时，通过使玩家对其他客户端可见来禁用隐身药水的效果。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'PreventDeadModification',     type: 'boolean', default: true,   category: '反作弊',     description: '禁止玩家在死亡状态下与游戏世界进行交互。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'PreventInvalidPlaceStyle',    type: 'boolean', default: true,   category: '反作弊',     description: '防止玩家放置具有无效风格的物块。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'BombExplosionRadius',         type: 'number',  default: 5,      category: '反作弊',     description: '确定炸弹从爆炸点开始影响方块的范围内，以方块为单位。 * **字段类型**: `Int32` * **默认值**: `5`' },
  { key: 'DisableClownBombs',           type: 'boolean', default: false,  category: '反作弊',     description: '禁用小丑炸弹射弹的生成。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'DisablePrimeBombs',           type: 'boolean', default: false,  category: '反作弊',     description: '禁用机械骷髅王炸弹生成，用于在"For The Worthy"种子世界中防止意外地形破坏 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'DisableSnowBalls',            type: 'boolean', default: false,  category: '反作弊',     description: '禁用雪人的雪球物块射弹。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'DisableModifiedZenith',       type: 'boolean', default: false,  category: '反作弊',     description: '禁止使用非天顶剑武器或篡改AI参数的天顶剑射弹。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'DisableDungeonGuardian',      type: 'boolean', default: false,  category: '反作弊',     description: '阻止地牢守卫生成，同时将玩家传送至其出生点。 * **字段类型**: `Boolean` * **默认值**: `False`' },

  // ── 保存与备份 ────────────────────────────────────────────────────
  { key: 'AutoSave',                    type: 'boolean', default: true,   category: '保存与备份', description: '启用或禁用泰拉瑞亚内置的世界自动保存功能。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'BackupInterval',              type: 'number',  default: 10,     category: '保存与备份', description: '备份间隔时间，以分钟为单位。备份文件存储在tshock/backups文件夹中。 * **字段类型**: `Int32` * **默认值**: `10`' },
  { key: 'BackupKeepFor',               type: 'number',  default: 240,    category: '保存与备份', description: '备份保留多长时间，以分钟计。 例如：2880 = 2天 * **字段类型**: `Int32` * **默认值**: `240`' },
  { key: 'SaveWorldOnCrash',            type: 'boolean', default: true,   category: '保存与备份', description: '如果服务器因未处理的异常而崩溃，是否保存世界。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'SaveWorldOnLastPlayerExit',   type: 'boolean', default: true,   category: '保存与备份', description: '当最后一个玩家断开连接时，是否保存世界。 * **字段类型**: `Boolean` * **默认值**: `True`' },

  // ── REST API ──────────────────────────────────────────────────────
  { key: 'RestApiEnabled',              type: 'boolean', default: false,  category: 'REST API', description: '启用或禁用REST API。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'RestApiPort',                 type: 'number',  default: 7878,   category: 'REST API', description: 'REST API使用的端口。 * **字段类型**: `Int32` * **默认值**: `7878`' },
  { key: 'EnableTokenEndpointAuthentication', type: 'boolean', default: false, category: 'REST API', description: '是否要求使用公共REST API端点时进行令牌认证。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'LogRest',                     type: 'boolean', default: false,  category: 'REST API', description: '是否记录REST API连接。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'RESTMaximumRequestsPerInterval', type: 'number', default: 5,   category: 'REST API', description: '在拒绝请求前，桶中允许的最大REST请求数。最小值为5。 * **字段类型**: `Int32` * **默认值**: `5`' },
  { key: 'RESTRequestBucketDecreaseIntervalMinutes', type: 'number', default: 1, category: 'REST API', description: 'REST请求桶每分钟减少一次的频率。最小值是1分钟。 * **字段类型**: `Int32` * **默认值**: `1`' },
  { key: 'ApplicationRestTokens',       type: 'rest_tokens', default: {}, category: 'REST API', description: '一个包含REST令牌的字典，外部应用程序可以使用这些令牌向您的服务器发起查询。 * **字段类型**: `Dictionary`2` * **默认值**: `System.Collections.Generic.Dictionary`2[System.String,Rests.SecureRest+TokenData]`' },

  // ── 数据库与日志 ──────────────────────────────────────────────────
  { key: 'StorageType',                 type: 'select',  default: 'sqlite', options: ['sqlite', 'mysql'], category: '数据库与日志', description: '存储数据时使用的数据库类型（”sqlite” 或 “mysql”）。 * **字段类型**: `String` * **默认值**: `sqlite`' },
  { key: 'SqliteDBPath',                type: 'string',  default: 'tshock.sqlite', category: '数据库与日志', description: 'sqlite数据库的路径。 * **字段类型**: `String` * **默认值**: `tshock.sqlite`' },
  { key: 'MySqlHost',                   type: 'string',  default: 'localhost:3306', category: '数据库与日志', description: '用于将连接定向到MySQL主机名和端口。 * **字段类型**: `String` * **默认值**: `localhost:3306`' },
  { key: 'MySqlDbName',                 type: 'string',  default: '',     category: '数据库与日志', description: '使用MySQL作为数据库类型时连接的数据库名称。 * **字段类型**: `String` * **默认值**: ``' },
  { key: 'MySqlUsername',               type: 'string',  default: '',     category: '数据库与日志', description: '连接到MySQL数据库时使用的用户名。 * **字段类型**: `String` * **默认值**: ``' },
  { key: 'MySqlPassword',               type: 'string',  default: '',     category: '数据库与日志', description: '连接到MySQL数据库时使用的密码。 * **字段类型**: `String` * **默认值**: ``' },
  { key: 'UseSqlLogs',                  type: 'boolean', default: false,  category: '数据库与日志', description: '是否将日志保存到SQL数据库而不是文本文件。 默认值 = false. * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'LogPath',                     type: 'string',  default: 'tshock/logs', category: '数据库与日志', description: '日志应写入的目录路径。 * **字段类型**: `String` * **默认值**: `tshock/logs`' },
  { key: 'DebugLogs',                   type: 'boolean', default: false,  category: '数据库与日志', description: '服务器是否应输出与系统操作相关的调试级别消息。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'DisableSpewLogs',             type: 'boolean', default: true,   category: '数据库与日志', description: '禁用向具有日志权限的玩家发送日志消息。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'DisableSecondUpdateLogs',     type: 'boolean', default: false,  category: '数据库与日志', description: '防止OnSecondUpdate检查写入日志文件。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'RevertToTextLogsOnSqlFailures',type:'number',  default: 10,     category: '数据库与日志', description: '在回退到文本日志之前，SQL日志插入失败必须达到的次数。 * **字段类型**: `Int32` * **默认值**: `10`' },
  { key: 'SuppressPermissionFailureNotices', type: 'boolean', default: false, category: '数据库与日志', description: '是否屏蔽玩家在受保护分区、出生点执行方块修改操作时弹出的提示。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'DisableCustomDeathMessages',  type: 'boolean', default: true,   category: '数据库与日志', description: '允许您禁用或启用防止创建自定义死亡消息的保护功能。专为那些为此问题提出了更具原创性解决方案的开发者而设计。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'DisableTombstones',           type: 'boolean', default: true,   category: '数据库与日志', description: '禁用所有玩家死亡时掉落墓碑。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'DisableDefaultIPBan',         type: 'boolean', default: false,  category: '数据库与日志', description: '如果没有传递参数给封禁命令，默认情况下禁用IP封禁。 * **字段类型**: `Boolean` * **默认值**: `False`' },
]

// SSC（服务端角色）配置文件 schema
export const SSC_SCHEMA = [
  { key: 'Enabled',                     type: 'boolean', default: false,  category: 'SSC 基础',   description: '启用服务器端角色功能，使客户端数据存储在服务器而非客户端。 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'KeepPlayerAppearance',        type: 'boolean', default: false,  category: 'SSC 基础',   description: 'SSC 模式下玩家角色外貌是否同步本地更新 * **字段类型**: `Boolean` * **默认值**: `False`' },
  { key: 'LogonDiscardThreshold',       type: 'number',  default: 250,    category: 'SSC 基础',   description: '当启用“服务器端角色”（ServerSideCharacters）功能时，登录后禁止丢弃物品的时间（以毫秒为单位）。 * **字段类型**: `Int32` * **默认值**: `250`' },
  { key: 'ServerSideCharacterSave',     type: 'number',  default: 5,      category: 'SSC 基础',   description: '服务器端角色（SSC）的自动保存间隔（以分钟为单位）。 * **字段类型**: `Int32` * **默认值**: `5`' },
  { key: 'StartingHealth',              type: 'number',  default: 100,    category: '初始属性',   description: '启用SSC功能时，新玩家创建角色时的初始默认生命值。 * **字段类型**: `Int32` * **默认值**: `100`' },
  { key: 'StartingMana',                type: 'number',  default: 20,     category: '初始属性',   description: '启用SSC功能时，新玩家创建角色时的初始默认魔力值。 * **字段类型**: `Int32` * **默认值**: `20`' },
  { key: 'WarnPlayersAboutBypassPermission', type: 'boolean', default: true, category: 'SSC 基础', description: '当玩家拥有`tshock.ignore.ssc`权限（可绕过SSC系统）但SSC数据库中仍存在其角色数据时，向玩家和服务器控制台发送警告信息。 * **字段类型**: `Boolean` * **默认值**: `True`' },
  { key: 'StartingInventory',           type: 'item_list', default: [],   category: '初始属性',   description: '启用SSC功能时，新玩家创建角色时的初始默认物品栏配置。 * **字段类型**: `List`1` * **默认值**: `System.Collections.Generic.List`1[TShockAPI.NetItem]`' },
]

// 配置文件映射
export const CONFIG_FILE_MAP = {
  config: {
    schema: CONFIG_SCHEMA,
    filename: 'config.json',
    title: 'TShock 主配置',
    subtitle: 'config.json',
  },
  ssc: {
    schema: SSC_SCHEMA,
    filename: 'sscconfig.json',
    title: 'SSC 服务端角色配置',
    subtitle: 'sscconfig.json',
  },
}
